version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8.10
  poke_npmrc: &poke_npmrc
    run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  save_npm_cache: &save_npm_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  dev:
    <<: *container_config
    steps:
      - *poke_npmrc
      - checkout
      - *restore_npm_cache
      - run: npm install
      - *save_npm_cache
      - run: npm run test
  
  live:
    <<: *container_config
    steps:
      - *poke_npmrc
      - checkout
      - *restore_npm_cache
      - run: npm install
      - *save_npm_cache
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - dev
      - live:
          requires:
            - dev
          filters:
            branches:
              only: master
